spring.application.name = Custom_Authentication


spring.datasource.url=jdbc:mysql://localhost:3306/email_verification_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=nabajit9


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=noboutsab@gmail.com
spring.mail.password=ibaj qmdv vzyt prhx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# JWT
jwt.secret=dGhpcyBpcyBhIHNlY3VyZSBqd3Qgc2VjcmV0IGtleSBmb3IgaHMyNTYhISE=
jwt.expiration=86400000





